# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{buddy}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Ole Riesenberg"]
  s.date = %q{2010-03-12}
  s.description = %q{buddybrand's facebook library}
  s.email = %q{labs@buddybrand.de}
  s.files = [
    "Rakefile",
     "VERSION.yml",
     "lib/fb_buddy.rb"
  ]
  s.homepage = %q{http://buddybrand.de}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{buddybrand's facebook library}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<mini_fb>, [">= 0.2.2"])
    else
      s.add_dependency(%q<mini_fb>, [">= 0.2.2"])
    end
  else
    s.add_dependency(%q<mini_fb>, [">= 0.2.2"])
  end
end
